USE SC_CRUD;

CREATE TABLE IF NOT EXISTS `SC_CRUD`.`ADDRESS` (
  `ID` VARCHAR(36) NOT NULL DEFAULT 'UUID()',
  `USER_ID` VARCHAR(36) NOT NULL,
  `ADDRESS_TYPE` VARCHAR(10) NOT NULL,
  `LINE_1` VARCHAR(50) NOT NULL,
  `LINE_2` VARCHAR(50) NULL,
  `LINE_3` VARCHAR(50) NULL,
  `LINE_4` VARCHAR(50) NULL,
  `COUNTRY_CODE` VARCHAR(5) NOT NULL,
  `ZIP_CODE` INT NOT NULL,
  `STATE` VARCHAR(50) NOT NULL,
  `CITY` VARCHAR(50) NOT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `UPDATED_TIMESTAMP` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`ID`),
  INDEX `USER_ID_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `SC_CRUD`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
